version : '3'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - ../database2:/data/db
    environment:
      MONGO_INITDB_DATABASE: root-db

networks:
  my-network:
    external:
      name: my-network