version : '3.9'

services:
  app:
    build:
      context: ${PWD}
      dockerfile: dockerfile.dev
    environment:
      - MONGODBHOST=mongodb://root:root@mongo:27017
      - MONGODB_DATABASE=ecommerce
    ports:
      - 4000:3000
    networks:
      - mynet
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    restart: always
    container_name: name
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mynet


networks:
  mynet:
    #external:
      #name: mynet
