version : '3.1'

services:
  mongo:
    image: mongo:4.4.18-rc0-focal
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB: ecommerse
      MONGOHOST: mongodb://localhost:27018
    volumes:
      - ../database:/data/db
